<?php

namespace app\modules\admin\controllers;

use app\common\helpers\Helper;
use app\common\models\CarType;
use app\common\models\Chapter;
use app\common\models\Question;
use app\common\models\Special;
use app\common\models\Subject;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii;

/**
 * Class QuestionController 题库信息
 * @package app\modules\admin\controllers
 */
class QuestionController extends Controller
{
    /**
     * where() 查询处理
     * @param  array $params
     * @return array 返回数组
     */
    public function where($params)
    {
        return [
            'status' => '=',
            'answer_type' => '=',
            'subject_id' => '=',
            'chapter_id' => '=',
            'special_id' => '=',
        ];
    }

    /**
     * actionIndex() 首页显示
     * @return string
     */
    public function actionIndex()
    {
        // 获取数据
        $special = Special::find()->where(['!=', 'pid', 0])->orderBy('sort')->all();
        $chapter = Chapter::find()->orderBy('sort')->all();
        // 查询考试类型
        $cars = CarType::findAll(['status' => 1]);

        $arrChapter = Helper::map($chapter, 'id', 'name');
        $arrSubject = Subject::getSubject();

        // 专项分类
        $special = Helper::map($special, 'id', 'name');

        return $this->render('index', [
            'cars' => Json::encode(ArrayHelper::map($cars, 'id', 'name')), // 类型
            'subject' => Json::encode($arrSubject['subject']), // 科目
            'arrSubject' => $arrSubject['subject'], // 科目信息,
            'car_subject' => Json::encode($arrSubject['car_subject']),
            'special' => Json::encode($special), // 专项
            'arrSpecial' => $special,
            'chapter' => Json::encode($arrChapter), // 章节
            'arrChapter' => $arrChapter,
            'status'  => Json::encode(Question::getStatusDesc()),           // 状态
            'color'  => Json::encode(Question::getStatusColor()),           // 状态颜色
            'type'  => Json::encode(Question::getTypeDesc()),               // 答案类型
        ]);
    }

    public function actionCreate()
    {
        $request = \Yii::$app->request;
        if ($request->isGet) {
            $intSubject = (int)$request->get('subject_id');
            $intChapter = (int)$request->get('chapter_id');
            if ($intChapter > 0) {
                $chapter = Chapter::findOne($intChapter);
                if ($chapter) {
                    $intSubject = $chapter->subject_id;
                } else {
                    $intChapter = 0;
                }
            }

            // 查询数据
            $special = Special::find()->where(['!=', 'pid', 0])->orderBy('sort')->all();
            $chapter = Chapter::find()->orderBy('sort')->all();
            $chapter[] = ['id' => 0, 'name' => '请选择'];
            $subject = Subject::getSubject();
            $subject[0] = '请选择';

            // 载入视图
            return $this->render('create', [
                'subject_id' => $intSubject,
                'chapter_id' => $intChapter,
                'subject' => $subject,
                'chapter' => ArrayHelper::map($chapter, 'id', 'name'),
                'types' => Question::getTypeDesc(),
                'special' => ArrayHelper::map($special, 'id', 'name')
            ]);
        } else {
            return parent::actionCreate(); // TODO: Change the autogenerated stub
        }
    }

    /**
     * actionSubject() 获取科目
     * @return mixed|string
     */
    public function actionSubject()
    {
        $request = \Yii::$app->request;
        if ($request->isAjax) {
            $intCid = (int)$request->post('cid');
            if ($intCid) {
                $subject = Subject::findAll(['status' => 1, 'car_id' => $intCid]);
                $this->handleJson($subject);
            }
        }

        return $this->returnJson();
    }

    /**
     * actionChapter() 获取章节
     * @return mixed|string
     */
    public function actionChapter()
    {
        $request = \Yii::$app->request;
        if ($request->isAjax) {
            $intSid = (int)$request->post('sid');
            if ($intSid) {
                $subject = Chapter::findAll(['subject_id' => $intSid]);
                $this->handleJson($subject);
            }
        }

        return $this->returnJson();
    }

    /**
     * 处理导入数据
     * @return mixed|string
     */
    public function actionUploadQuestion()
    {
        $request = \Yii::$app->request;
        if ($request->isAjax) {
            $intSubject = (int)$request->post('subject_id'); // 科目信息
            $intChapter = (int)$request->post('chapter_id'); // 章节信息
            $intSpecial = (int)$request->post('special_id'); // 专项信息
            $strFile = trim($request->post('upload_file'));

            // 验证提交数据
            if (($intSubject || $intChapter) && $strFile) {
                // 查询出全部专项信息
                $arrSpecial = Special::find()->where(['!=', 'pid', 0])->indexBy('name')->all();

                $objPHPExcel = \PHPExcel_IOFactory::load('.'.$strFile);
                if ($objPHPExcel) {
                    $objWorksheet = $objPHPExcel->getActiveSheet();
                    $intRows = $objWorksheet->getHighestRow(); // 获取总行数

                    // 读取数据的第二行
                    $array = [];
                    $time = time();
                    $fields = [
                        'question_title',
                        'question_content',
                        'answer_type',
                        'answers',
                        'answer_id',
                        'subject_id',
                        'chapter_id',
                        'created_at',
                        'updated_at',
                        'special_id',
                    ];

                    $db = Yii::$app->db;
                    for ($i = 2; $i <= $intRows; $i ++) {
                        // 获取题目类型
                        $intAnswerType = (int)$objWorksheet->getCell('C'.$i)->getValue();

                        // 获取正确答案信息
                        $answer = trim($objWorksheet->getCell('E'.$i)->getValue());
                        if ($intAnswerType === Question::ANSWER_TYPE_MULTI) {
                            $mixAnswerId = explode(',', $answer);
                            $mixAnswerId = array_map(function($value) {
                                return $value - 1;
                            }, $mixAnswerId);
                            $mixAnswerId = Json::encode($mixAnswerId);
                        } else {
                            $mixAnswerId = $answer > 0 ? (int)$answer - 1 : 0;
                        }

                        // 处理专项信息
                        $special = trim($objWorksheet->getCell('F'.$i)->getValue());
                        if ($special && isset($arrSpecial[$special])) {
                            $special = $arrSpecial[$special]->id;
                        } else {
                            $special = $intSpecial;
                        }

                        $array[] = [
                            $objWorksheet->getCell('A'.$i)->getValue(),
                            $objWorksheet->getCell('B'.$i)->getValue(),
                            $intAnswerType,
                            Json::encode(explode('|', $objWorksheet->getCell('D'.$i)->getValue())),
                            $mixAnswerId,
                            $intSubject,
                            $intChapter,
                            $time,
                            $time,
                            $special,
                        ];

                        // 所有数据
                        if (count($array) >= 100) {
                            if ($db->createCommand()->batchInsert(
                                '{{%question}}',
                                $fields,
                                $array
                            )->execute()) {
                                $array = [];
                            }
                        }
                    }

                    if (!empty($array)) {
                        if ($db->createCommand()->batchInsert(
                            '{{%question}}',
                            $fields,
                            $array
                        )->execute()) {
                            $isTrue = true;
                        } else {
                            $isTrue = false;
                        }
                    } else {
                        $isTrue = true;
                    }

                    $this->arrJson['errMsg'] = '上传题目处理失败';
                    if ($isTrue) {
                        $this->handleJson($array, 0, '上传题目处理成功');
                    }
                }
            }
        }

        return $this->returnJson();
    }

    /**
     * getModel() 返回model
     * @return Question
     */
    public function getModel()
    {
        return new Question();
    }
}
